# Generated by Django 4.2 on 2023-04-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
